/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExecutiveTeamRouteImport } from './routes/executive-team'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as RegistrationRouteImport } from './routes/registration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveTeamRoute = ExecutiveTeamRouteImport.update({
  id: '/executive-team',
  path: '/executive-team',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/executive-team': typeof ExecutiveTeamRoute
  '/guides': typeof GuidesRoute
  '/logistics': typeof LogisticsRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/executive-team': typeof ExecutiveTeamRoute
  '/guides': typeof GuidesRoute
  '/logistics': typeof LogisticsRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/executive-team': typeof ExecutiveTeamRoute
  '/guides': typeof GuidesRoute
  '/logistics': typeof LogisticsRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committees'
    | '/contact'
    | '/executive-team'
    | '/guides'
    | '/logistics'
    | '/registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committees'
    | '/contact'
    | '/executive-team'
    | '/guides'
    | '/logistics'
    | '/registration'
  id:
    | '__root__'
    | '/'
    | '/committees'
    | '/contact'
    | '/executive-team'
    | '/guides'
    | '/logistics'
    | '/registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteesRoute: typeof CommitteesRoute
  ContactRoute: typeof ContactRoute
  ExecutiveTeamRoute: typeof ExecutiveTeamRoute
  GuidesRoute: typeof GuidesRoute
  LogisticsRoute: typeof LogisticsRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-team': {
      id: '/executive-team'
      path: '/executive-team'
      fullPath: '/executive-team'
      preLoaderRoute: typeof ExecutiveTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteesRoute: CommitteesRoute,
  ContactRoute: ContactRoute,
  ExecutiveTeamRoute: ExecutiveTeamRoute,
  GuidesRoute: GuidesRoute,
  LogisticsRoute: LogisticsRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
